name: SANDBOX

on:
  workflow_dispatch:
    inputs:
      execution:
        description: 'Insira o teste que você quer executar ou deixe em branco para executar todos os testes.'
        required: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar ambiente
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
      shell: bash

    - name: Baixar e configurar o Chromedriver
      run: |
        curl -O https://chromedriver.storage.googleapis.com/94.0.4606.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/
      shell: bash

    - name: Instalar o Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
      shell: bash

    - name: Configurar ambiente virtual e instalar dependências
      run: |
        python -m venv ambiente-teste
        source ambiente-teste/bin/activate
        pip install -U pytest selenium
      shell: bash -l

    - name: Executar testes
      run: |
        if [ -z "${{ inputs.execution }}" ]; then
          pytest -v tests/
        else
          pytest -v -k "${{ inputs.execution }}"
        fi
      shell: bash
